### ISSUE TITLE
Builded version doesn't have "opts" default parameter in quantize function

### ISSUE THREAD

**Issue by roquef** [mattdesl/gifenc#7]
When using the builded version the function quantize(rgba, maxColors, opts = {}) doesn't have a default parameter for "opts", if you call quantize() without options it breaks the execution:

Cannot read property 'useSqrt' of undefined (opts is undefined, no default parameter)

If i build it manually it doesn't happen, tested with unpkg and repo master dist folder versions.

https://github.com/mattdesl/gifenc/blob/a5a5df24234a47693f499ce375b4b8a1676132a8/dist/gifenc.js#L359

**Comment by mattdesl** [comment]
Thanks! Fixed in 1.0.3.
